export const floodData = [
  {
    place: "Mavoor Road Junction",
    exact_location: "Near Baby Memorial Hospital",
    flood_count: 9,
    risk_level: "High",
  },
  {
    place: "Palayam Junction",
    exact_location: "Palayam Bus Stand Area",
    flood_count: 8,
    risk_level: "High",
  },
  {
    place: "Puthiyangadi",
    exact_location: "Coastal Belt",
    flood_count: 10,
    risk_level: "High",
  },
  {
    place: "Kallai",
    exact_location: "Kallai River Bank",
    flood_count: 9,
    risk_level: "High",
  },
  {
    place: "Vellimadukunnu",
    exact_location: "Near Medical College",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Karanthur",
    exact_location: "Near NIT Calicut",
    flood_count: 5,
    risk_level: "Medium",
  },
  {
    place: "Thiruthiyad",
    exact_location: "Market Area",
    flood_count: 7,
    risk_level: "High",
  },
  {
    place: "Kovoor",
    exact_location: "Kovoor Junction",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Kottooli",
    exact_location: "Near Focus Mall",
    flood_count: 5,
    risk_level: "Medium",
  },
  {
    place: "West Hill",
    exact_location: "Residential Area",
    flood_count: 4,
    risk_level: "Low",
  },
  {
    place: "Cherooty Road",
    exact_location: "City Center",
    flood_count: 7,
    risk_level: "High",
  },
  {
    place: "Vellayil",
    exact_location: "Near Vellayil Beach",
    flood_count: 8,
    risk_level: "High",
  },
  {
    place: "Eranhipalam",
    exact_location: "Near Eranhipalam Junction",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Nadakkavu",
    exact_location: "Near Police Station",
    flood_count: 7,
    risk_level: "High",
  },
  {
    place: "Pantheerankavu",
    exact_location: "Suburban Area",
    flood_count: 5,
    risk_level: "Medium",
  },
  {
    place: "Elathur",
    exact_location: "Coastal Region",
    flood_count: 8,
    risk_level: "High",
  },
  {
    place: "Kakkodi",
    exact_location: "Town Area",
    flood_count: 4,
    risk_level: "Low",
  },
  {
    place: "Chelavoor",
    exact_location: "Junction Area",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Peruvannamuzhi",
    exact_location: "Near Reservoir",
    flood_count: 5,
    risk_level: "Medium",
  },
  {
    place: "Kuttikkattoor",
    exact_location: "Suburban Area",
    flood_count: 4,
    risk_level: "Low",
  },
  {
    place: "Feroke",
    exact_location: "Chaliyar River Bank",
    flood_count: 10,
    risk_level: "High",
  },
  {
    place: "Beypore",
    exact_location: "Harbour Area",
    flood_count: 10,
    risk_level: "High",
  },
  {
    place: "Cheruvannur",
    exact_location: "Town Center",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Ramanattukara",
    exact_location: "Bypass Junction",
    flood_count: 7,
    risk_level: "High",
  },
  {
    place: "Kondotty Road Area",
    exact_location: "Low-lying Zone",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Kunnamangalam",
    exact_location: "Town Center",
    flood_count: 5,
    risk_level: "Medium",
  },
  {
    place: "Mukkam",
    exact_location: "Near Iruvanjippuzha River",
    flood_count: 9,
    risk_level: "High",
  },
  {
    place: "Thamarassery",
    exact_location: "Highway Stretch",
    flood_count: 5,
    risk_level: "Medium",
  },
  {
    place: "Koodaranji",
    exact_location: "Valley Area",
    flood_count: 4,
    risk_level: "Low",
  },
  {
    place: "Kodenchery",
    exact_location: "Hill Foothills",
    flood_count: 4,
    risk_level: "Low",
  },
  {
    place: "Koyilandy",
    exact_location: "Coastal Town",
    flood_count: 8,
    risk_level: "High",
  },
  {
    place: "Payyoli",
    exact_location: "Coastal Belt",
    flood_count: 8,
    risk_level: "High",
  },
  {
    place: "Vadakara",
    exact_location: "Kuttiyadi River Area",
    flood_count: 7,
    risk_level: "High",
  },
  {
    place: "Nadapuram",
    exact_location: "Low-lying Area",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Thottilpalam",
    exact_location: "Near Kuttiyadi River",
    flood_count: 7,
    risk_level: "High",
  },
  {
    place: "Kuttyadi",
    exact_location: "Reservoir Backwater Area",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Balussery",
    exact_location: "Town Center",
    flood_count: 5,
    risk_level: "Medium",
  },
  {
    place: "Panangad",
    exact_location: "Backwater Zone",
    flood_count: 7,
    risk_level: "High",
  },
  {
    place: "Chemancheri",
    exact_location: "Coastal Area",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Edachery",
    exact_location: "Low-lying Zone",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Kakkattil",
    exact_location: "River Basin Area",
    flood_count: 7,
    risk_level: "High",
  },
  {
    place: "Azhiyur",
    exact_location: "Coastal Belt",
    flood_count: 8,
    risk_level: "High",
  },
  {
    place: "Chorode",
    exact_location: "Low-lying Coastal Area",
    flood_count: 7,
    risk_level: "High",
  },
  {
    place: "Thikkodi",
    exact_location: "Coastal Village",
    flood_count: 7,
    risk_level: "High",
  },
  {
    place: "Vilangad",
    exact_location: "Hilly Valley Area",
    flood_count: 4,
    risk_level: "Low",
  },
  {
    place: "Maniyur",
    exact_location: "Low-lying Agricultural Belt",
    flood_count: 5,
    risk_level: "Medium",
  },
  {
    place: "Kavilumpara",
    exact_location: "River Basin Area",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Perambra",
    exact_location: "Town Center",
    flood_count: 5,
    risk_level: "Medium",
  },
  {
    place: "Kayanna",
    exact_location: "Valley Region",
    flood_count: 4,
    risk_level: "Low",
  },
  {
    place: "Vatakara Town",
    exact_location: "Market Area",
    flood_count: 8,
    risk_level: "High",
  },
  {
    place: "Kuttiady Town",
    exact_location: "Riverbank Area",
    flood_count: 7,
    risk_level: "High",
  },
  {
    place: "Meppayur",
    exact_location: "Low-lying Zone",
    flood_count: 5,
    risk_level: "Medium",
  },
  {
    place: "Moodadi",
    exact_location: "Coastal Area",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Ariyallur",
    exact_location: "Backwater Belt",
    flood_count: 7,
    risk_level: "High",
  },
  {
    place: "Thuneri",
    exact_location: "Low-lying Region",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Thiruvallur",
    exact_location: "Near River",
    flood_count: 7,
    risk_level: "High",
  },
  {
    place: "Chekkiad",
    exact_location: "Coastal Belt",
    flood_count: 7,
    risk_level: "High",
  },
  {
    place: "Narikkuni",
    exact_location: "Town Center",
    flood_count: 5,
    risk_level: "Medium",
  },
  {
    place: "Atholi",
    exact_location: "Low-lying Area",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Kakkur",
    exact_location: "Near Riverbank",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Kuruvattur",
    exact_location: "Urban Flood Zone",
    flood_count: 7,
    risk_level: "High",
  },
  {
    place: "Kunnummal",
    exact_location: "Hilly Foothills",
    flood_count: 4,
    risk_level: "Low",
  },
  {
    place: "Karaparamba",
    exact_location: "City Outskirts",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Pooladikunnu",
    exact_location: "Residential Area",
    flood_count: 5,
    risk_level: "Medium",
  },
  {
    place: "Malaparamba",
    exact_location: "Urban Area",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Farook College Area",
    exact_location: "Near Chaliyar River",
    flood_count: 9,
    risk_level: "High",
  },
  {
    place: "Chaliyam",
    exact_location: "Backwater Zone",
    flood_count: 9,
    risk_level: "High",
  },
  {
    place: "Iringal",
    exact_location: "Coastal Belt",
    flood_count: 8,
    risk_level: "High",
  },
  {
    place: "Orkatteri",
    exact_location: "Town Center",
    flood_count: 5,
    risk_level: "Medium",
  },
  {
    place: "Thiruvambady",
    exact_location: "Valley Area",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Omassery",
    exact_location: "Low-lying Zone",
    flood_count: 5,
    risk_level: "Medium",
  },
  {
    place: "Panniyankara",
    exact_location: "Urban Slum Belt",
    flood_count: 8,
    risk_level: "High",
  },
  {
    place: "Puthiyara",
    exact_location: "City Area",
    flood_count: 7,
    risk_level: "High",
  },
  {
    place: "Calicut Beach Area",
    exact_location: "Coastal Belt",
    flood_count: 10,
    risk_level: "High",
  },
  {
    place: "Kadalundi",
    exact_location: "Kadalundi River Mouth",
    flood_count: 10,
    risk_level: "High",
  },
  {
    place: "Parambil Bazar",
    exact_location: "Town Center",
    flood_count: 5,
    risk_level: "Medium",
  },
  {
    place: "Kattangal",
    exact_location: "Industrial Area",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Cheruvatta",
    exact_location: "Low-lying Area",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Nanminda",
    exact_location: "Agricultural Belt",
    flood_count: 5,
    risk_level: "Medium",
  },
  {
    place: "Koorachundu",
    exact_location: "Hilly Valley Area",
    flood_count: 4,
    risk_level: "Low",
  },
  {
    place: "Kodenchery Road Area",
    exact_location: "Riverbank Stretch",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Adivaram",
    exact_location: "Valley Foothills",
    flood_count: 4,
    risk_level: "Low",
  },
  {
    place: "Thalayad",
    exact_location: "Hilly Region",
    flood_count: 4,
    risk_level: "Low",
  },
  {
    place: "Palazhi",
    exact_location: "Urban Waterlogging Zone",
    flood_count: 7,
    risk_level: "High",
  },
  {
    place: "Kottuli",
    exact_location: "Near Canal",
    flood_count: 7,
    risk_level: "High",
  },
  {
    place: "Puthiyangadi Beach",
    exact_location: "Coastal Zone",
    flood_count: 9,
    risk_level: "High",
  },
  {
    place: "Thondayad",
    exact_location: "Residential Area",
    flood_count: 5,
    risk_level: "Medium",
  },
  {
    place: "Kunnamangalam Market",
    exact_location: "Town Center",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Mankavu",
    exact_location: "Low-lying Urban Zone",
    flood_count: 7,
    risk_level: "High",
  },
  {
    place: "Medical College Area",
    exact_location: "Drainage-Prone Zone",
    flood_count: 8,
    risk_level: "High",
  },
  {
    place: "Kozhikode Railway Station Area",
    exact_location: "Urban Flood Zone",
    flood_count: 9,
    risk_level: "High",
  },
  {
    place: "Karuvanthuruthy",
    exact_location: "Backwater Belt",
    flood_count: 7,
    risk_level: "High",
  },
  {
    place: "Poonoor",
    exact_location: "Low-lying Area",
    flood_count: 5,
    risk_level: "Medium",
  },
  {
    place: "Thazhekode",
    exact_location: "Valley Belt",
    flood_count: 5,
    risk_level: "Medium",
  },
  {
    place: "Mavoor Town",
    exact_location: "Near Chaliyar",
    flood_count: 8,
    risk_level: "High",
  },
  {
    place: "Velliparamba",
    exact_location: "Urban Area",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Chevayur",
    exact_location: "Residential Area",
    flood_count: 5,
    risk_level: "Medium",
  },
  {
    place: "Kuthiravattam",
    exact_location: "Low-lying Belt",
    flood_count: 6,
    risk_level: "Medium",
  },
  {
    place: "Perumanna",
    exact_location: "Backwater Area",
    flood_count: 7,
    risk_level: "High",
  },
  {
    place: "Kadalundi Nagaram",
    exact_location: "River Mouth",
    flood_count: 9,
    risk_level: "High",
  },
  {
    place: "Ramanattukara Bypass",
    exact_location: "Drainage Zone",
    flood_count: 8,
    risk_level: "High",
  },
  {
    place: "Kozhikode Civil Station",
    exact_location: "Urban Flood Zone",
    flood_count: 7,
    risk_level: "High",
  },
  {
    place: "Puthiyara Canal Area",
    exact_location: "Canal Belt",
    flood_count: 8,
    risk_level: "High",
  },
];
